name: Build Vanish-OS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Archiso Builder Container
        run: |
          docker run --privileged --rm \
            -v ${{ github.workspace }}:/workspace \
            archlinux:base-devel \
            bash -c "chmod +x /workspace/build/build_iso.sh && /workspace/build/build_iso.sh"

      - name: Upload Vanish-OS ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vanish-os-zen-x86_64
          path: out/*.iso
          retention-days: 14
